import { createServerClient } from '@supabase/ssr';
import { NextResponse, type NextRequest } from 'next/server';

export async function updateSession(request: NextRequest) {
  let supabaseResponse = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          supabaseResponse = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options)
          );
        },
      },
    }
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();

  // A published, non-executive meeting's agenda export lives under the
  // otherwise-protected /meetings/* prefix (it's generated by the same
  // staff dashboard route), but is public record -- same boundary the
  // /agenda/[meetingId] page and the agenda-documents storage policy
  // already use. The route itself re-checks published/meeting_type before
  // serving anything; this only lets an anonymous request past the
  // middleware far enough to reach that check.
  const isPublicAgendaExport = /^\/meetings\/[^/]+\/agenda\/(pdf|docx)\/?$/.test(request.nextUrl.pathname);

  // The site is public by default (the InMC discover pages, agenda,
  // check-in, the rental request form); only the staff dashboard needs a
  // session. Listing the few protected prefixes here is less error-prone
  // than an allowlist that has to be remembered for every new public route.
  const isProtectedRoute = !isPublicAgendaExport && [
    '/meetings',
    '/board-members',
    '/staff',
    '/tabled-items',
    '/public-comments',
    '/notes',
    '/print',
    '/event-reviews',
    '/rentals',
    '/search',
    '/activity',
    '/finance-export',
    '/vendors',
    '/vendor-portal',
    '/board-portal',
    '/employees',
    '/employee-portal',
    '/partners',
    '/partner-portal',
    '/work-orders',
    '/scheduling',
    '/messages',
    '/sponsors',
    '/programs',
  ].some((prefix) => request.nextUrl.pathname.startsWith(prefix));

  if (!user && isProtectedRoute) {
    const url = request.nextUrl.clone();
    url.pathname = '/login';
    return NextResponse.redirect(url);
  }

  if (user && request.nextUrl.pathname === '/login') {
    // Everyone lands on the same personal account page regardless of which
    // roles they hold -- /me itself looks up vendor/employee/board/admin/
    // contributor access and shows a card for whichever apply, rather than
    // this sorting people into separate portals before they ever see it.
    const url = request.nextUrl.clone();
    url.pathname = '/me';
    return NextResponse.redirect(url);
  }

  return supabaseResponse;
}
